// Generated by CoffeeScript 1.6.2
define(function(require) {
  var Path;

  return Path = (function() {
    function Path(points) {
      this.points = points || [];
    }

    Path.prototype.addPoint = function(p) {
      return this.points.push(p);
    };

    return Path;

  })();
});
